# Heart Disease Prediction Using ANN(DL)


* **Intrdouction**
  *  Heart disease prediction using Artificial Neural Networks (ANN) is a cutting-edge approach in medical diagnostics that leverages the power of machine learning to assess an individual's risk of developing cardiovascular diseases.
  * This method employs complex computational models designed to mimic the human brain's neural networks, enabling the system to learn from large datasets and make predictions based on patterns it identifies.

*  **About the data:**
   *  In the dataset, we have 13 columns in which we are given different attributes such as sex, age, cholesterol level, etc. and we are given a target column which tells us whether that person has heart disease or not.
  *  We will keep all the columns as independent variables other than the target column because it will be our dependent variable.
   *  We will build an ANN which will predict whether a person has heart disease or not given other attributes of the person.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv("/content/heart.csv")
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

*Columns on Datasets*

In [3]:
data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

*Dtypes of Data*

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


*Some Statistical information of Datasets*

In [5]:
data.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

*Finding out Null values in Dataset*

In [6]:
data.isna().sum().sum()

0

*Total Rows & Columns of Datasets*

In [7]:
print("Total Rows in Datasets--->",data.shape[0])
print("Total Columns in Datasets--->",data.shape[1])

Total Rows in Datasets---> 1025
Total Columns in Datasets---> 14


*Separting into Dependent & Idependent Variable*

In [8]:
X = data.iloc[:,:13].values
y = data["target"].values

In [9]:
print(X)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


In [10]:
print(y)

[0 0 0 ... 0 1 0]


*Spliting into Train & Test Dataset*

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

*Building the Model*

In [12]:
model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(activation='relu',input_dim=13,units=8,kernel_initializer='uniform'))
model.add(tf.keras.layers.Dense(activation='relu',units=14,kernel_initializer='uniform'))
model.add(tf.keras.layers.Dense(activation='sigmoid',units=1,kernel_initializer='uniform'))

In [13]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 112       
                                                                 
 dense_1 (Dense)             (None, 14)                126       
                                                                 
 dense_2 (Dense)             (None, 1)                 15        
                                                                 
Total params: 253 (1012.00 Byte)
Trainable params: 253 (1012.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


*Fitting the Model*

In [16]:
model.fit(X_train , y_train , batch_size = 8 ,epochs = 100)

Epoch 1/100
90/90 [==============================] - 1s 2ms/step - loss: 0.6920 - accuracy: 0.5077
Epoch 2/100
90/90 [==============================] - 0s 2ms/step - loss: 0.6839 - accuracy: 0.5732
Epoch 3/100
90/90 [==============================] - 0s 2ms/step - loss: 0.6439 - accuracy: 0.6513
Epoch 4/100
90/90 [==============================] - 0s 3ms/step - loss: 0.5771 - accuracy: 0.7043
Epoch 5/100
90/90 [==============================] - 0s 2ms/step - loss: 0.5444 - accuracy: 0.7211
Epoch 6/100
90/90 [==============================] - 0s 2ms/step - loss: 0.5261 - accuracy: 0.7266
Epoch 7/100
90/90 [==============================] - 0s 2ms/step - loss: 0.5057 - accuracy: 0.7448
Epoch 8/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4983 - accuracy: 0.7476
Epoch 9/100
90/90 [==============================] - 0s 3ms/step - loss: 0.4803 - accuracy: 0.7587
Epoch 10/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4864 - accuracy: 0.7601
Epoch 11/

In [18]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

10/10 [==============================] - 0s 3ms/step


*Confusion Matrix*

In [19]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[121,  24],
       [ 15, 148]])

*Checking Accuracy*

In [20]:
accuracy = (cm[0][0]+cm[1][1])/(cm[0][1] + cm[1][0] +cm[0][0] +cm[1][1])  #Accuracy Formula
print(accuracy*100)


87.33766233766234


We will get accuracy approximately around 87&